version: '3.9'

networks:
  main.network:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: ${DOCKER_NAME}.nginx
    restart: always
    tty: true
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php 
    networks:
      - main.network
  mysql:
    image: mysql:8
    restart: always
    container_name: ${DOCKER_NAME}.mysql
    networks:
      - main.network
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development
    volumes:
      - "./mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./mysql/dbdata:/var/lib/mysql"
      - "./mysql/sample:/data"
    cap_add:
      - SYS_NICE
  phpmyadmin:
    image: library/phpmyadmin
    container_name: ${DOCKER_NAME}.phpmyadmin
    tty: true
    networks:
      - main.network
    depends_on:
      - php
      - mysql
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOSTS: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    restart: always
    tty: true
    container_name: ${DOCKER_NAME}.php
    networks:
      - main.network
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: ${DOCKER_NAME}.composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

